### ISSUE TITLE
Analytics is not supported in all regions

### ISSUE THREAD

**Issue by hbougdal** [apigee/devrel#103]
When setting the env variable $REGION (and $ZONE), it is worth mentioning that the Analytics are not available in all regions. If a user chooses a $REGION where Analytics are not available, the script fails.

**Comment by seymen** [comment]
Is this related to `hybrid-quickstart`?

**Comment by hbougdal** [comment]
yes

**Comment by danistrebel** [comment]
Fixed. @hbougdal
