### ISSUE TITLE
Should we suggest a folder template?

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#12]
Such as [here](https://github.com/ApigeeEMEA/demo-category-template) ?

**Comment by laughingbiscuit** [comment]
think about template versioning, as they are likely to change over time

**Comment by laughingbiscuit** [comment]
we can recommend the hello-world structure and improve that

**Comment by seymen** [comment]
We need to add ./generated folder in the contrib. I am not too hot on a standardised folder template but I have nothing against it either.

**Comment by laughingbiscuit** [comment]
`./references/proxy-template`can be used to bootstrap an Apigee proxy, suitable for a devrel project.
