### ISSUE TITLE
dynamically create service account for gcp-sa-auth-shared-flow 

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#120]
settting up the variables is a little clunky for new users - can we automate this as part of the pipeline?

**Comment by seymen** [comment]
If we are still blocked to dynamically create this in our gcp project (e.g. project access), then we should document how a fork can reproduce this and test.

**Comment by danistrebel** [comment]
Having IAM permissions to create service accounts from within the pipeline might pose some additional security risk.

I acknowledge the clunkiness point though. We could provide the instructions as a 2-line shell scripts for users to get set up quickly?

**Comment by seymen** [comment]
Happy with that.

**Comment by laughingbiscuit** [comment]
this has been added to the pipeline
