### ISSUE TITLE
Add postman collections as tests to Hello World project

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#13]
e.g. https://github.com/ApigeeEMEA/demo-general-circuit-breaker/blob/master/postman/Circuit%20Breaker%20Cache.postman_collection.json

**Comment by seymen** [comment]
Let's just pick a tool to demonstrate the existance of tests that asserts functionality that is implemented. apickli, mocha, jasmine, bob, etc.

**Comment by laughingbiscuit** [comment]
we are using apickli tests in template-proxy
