### ISSUE TITLE
Apigee NG requires that the cache entry has an expiry time for a cache resource

### ISSUE THREAD

**Issue by davidmitchell2019** [apigee/devrel#144]
Apigee NG requires that the cache entry has an expiry time for a cache resource.
When the shared flow does a lookup on the cache entry it exists, but when the set am header policy tries to add the bearer token it cant find the entry

**Comment by davidmitchell2019** [comment]
<PopulateCache name="PCCacheAccessToken">
    <CacheKey>
        <Prefix>gcp.sa</Prefix>
        <KeyFragment ref="private.gcp.service_account.client_id"/>
        <KeyFragment ref="token.purpose"/>
    </CacheKey>
    <CacheResource>gcp-tokens</CacheResource>
    <Source>private.gcp.access_token</Source>
    <ExpirySettings>
        <TimeoutInSec>600</TimeoutInSec>
    </ExpirySettings>
</PopulateCache>

**Comment by davidmitchell2019** [comment]
`<PopulateCache name="PCCacheAccessToken">
    <CacheKey>
        <Prefix>gcp.sa</Prefix>
        <KeyFragment ref="private.gcp.service_account.client_id"/>
        <KeyFragment ref="token.purpose"/>
    </CacheKey>
    <CacheResource>gcp-tokens</CacheResource>
    <Source>private.gcp.access_token</Source>
    <ExpirySettings>
        <TimeoutInSec>600</TimeoutInSec>
    </ExpirySettings>
</PopulateCache>`

**Comment by davidmitchell2019** [comment]
<img width="1170" alt="Screenshot 2021-01-06 at 13 28 55" src="https://user-images.githubusercontent.com/50448608/103773605-3b115080-5023-11eb-8cc3-365fc267dcab.png">

**Comment by davidmitchell2019** [comment]
So the lookup still finds the entry even tho the entry has expired

**Comment by tyayers** [comment]
Maybe an issue with TimeoutInSec, which is deprecated?  Try TimeoutInSeconds, haven't tested it in NG yet but could be the problem..

**Comment by davidmitchell2019** [comment]
Syntax error on my behalf, have a great day :-)

**Comment by danistrebel** [comment]
Thanks for reporting this. I can confirm the requirement for the ExpirySettings entry. 

I am a bit worried because the validation only allows for the deprecated `TimeoutInSec` instead of `TimeoutInSeconds`. I'll look into this and make some adjustment to the sharedflow based on that.
