### ISSUE TITLE
DevRel feature branch improvements

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#164]
to ease the review process, we only want PRs to applied to one project. if they apply to many, the should be split into multiple PRs to make the review simpler. The only exceptions to his are top level changes (e.g. eslint, github config) which are generally made by admins. these changes can be considered exceptions

in additional, it will significantly speed up the builds during the review process

pseudo logic
```
IF only one project has been changed
  run pipeline only for that project
ELSE 
  fail instead of running all projects. in exceptional cases we will manually trigger the build
FI
```

**Comment by laughingbiscuit** [comment]
in addition - if NO git history, then allow it to be specified

**Comment by danistrebel** [comment]
Proposal in the PR

PR builds only build changed projects. We have a preference for PRs to only one project at a time but this is not enforced at the pipeline level in favor of more flexibility.
Nightly builds build all pipelines
Manual Pipelines can specify one or more projects to be built using the `_CI_PROJECT` substitution (csv in case of more than one)
