### ISSUE TITLE
Testing hybrid proxy decryption

### ISSUE THREAD

**Issue by seymen** [apigee/devrel#173]
- Get a hybrid org
- Create a noddy proxy
- Go in the cluster and retrieve the encrypted source
- Put that archive in devrel project, run the script and grep for <ProxyEndpoint> and other strings in the source in various locations in the folder tree.

**Comment by yuriylesyuk** [comment]
Good suggestion. Thank you. I'll pick this issue up.

**Comment by seymen** [comment]
@yuriylesyuk - possible to pick this up whenever you are available please?
