### ISSUE TITLE
apigee-x-trial-provisioning: Make external exposure optional

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#186]
Currently the script always exposes the trial org externally. This is in the spirit of the project as if you only want internal exposure, then the UI Wizard is typically enough. However it would be nice to have this feature for completeness.

**Comment by OmidTahouri** [comment]
For internal-only exposure, it is advised to take the `gcloud alpha apigee organizations provision` approach, as documented here: https://cloud.google.com/apigee/docs/api-platform/get-started/install-cli-eval

For more customised deployments, explore a Terraform approach: https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/master/modules/apigee-organization
