### ISSUE TITLE
devrel/references/identity-facade/apiproxy/policies/RF-InvalidRequest-Redirect.xml errors during proxy deployment 

### ISSUE THREAD

**Issue by davormilutinovic** [apigee/devrel#217]
Hi,

current code is 
.....
&lt;StatusCode&gt;302&lt;/StatusCode&gt;
&lt;ReasonPhrase&gt;Found&lt;/ReasonPhrase&gt;
&lt;/Set&gt;
&lt;IgnoreUnresolvedVariables&gt;false&lt;/IgnoreUnresolvedVariables&gt;
&lt;AssignTo createNew=&quot;false&quot; type=&quot;response&quot;/&gt;
&lt;/FaultResponse&gt;
&lt;/RaiseFault&gt;

I think that &lt;IgnoreUnresolvedVariables .. line should be below &lt;/FaultResponse line and &lt;AssignTo createNew="false" type="response"/ line is not needed

**Comment by laughingbiscuit** [comment]
@JoelGauci do you have time to look at this, or shall I?
