### ISSUE TITLE
Support 5g for Common Shared Flows

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#250]
Raised by @apickelsimer via email - `references/common-shared-flows` is missing 5g deploy instructions.

Discussed with @danistrebel and we will extend `tools/portable-proxy-deployer` to abstract the deploy command for 4 and 5g

**Comment by danistrebel** [comment]
Sackmesser can be used to deploy to X/hybrid as well as Edge. See Readme in common shared flows solution.
