### ISSUE TITLE
Apigee hybrid quickstart

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#256]
1) When an environment group failed to be created, the current logic meant that the script continued instead of stopping and failing. This is either because `wait_for_ready()` didn't return a non-zero status code or the response code of the `POST` call to create the envgroup wasnt respected.

2) the scoping of variables is a bit inconsistent in the script. e.g. if i run `configure_network()` standalone without `set_config_params()` then there are some missing variables. If we want functions to be run standalone, lets call `set_config_params()` as the first line of each function.

**Comment by danistrebel** [comment]
Thanks @laughingbiscuit should probably be two separate issues:

1 in is taken care of by #258 

2 agreed. Currently running the functions in isolation is not a well supported use case of the hybrid quickstart and requires some internal knowledge (e.g. run the set_config_params function or order dependency). We also have [AHR](https://github.com/apigee/ahr) to perform exactly these tasks so I am wondering if we should invest time in duplicating the effort building another CLI in parallel.
