### ISSUE TITLE
kvm-admin-api: AM-SetReponse can produce invalid JSON

### ISSUE THREAD

**Issue by micovery** [apigee/devrel#274]
https://github.com/apigee/devrel/blob/36a9d863e67b3bbc964e567828f4d7a0818e9155/references/kvm-admin-api/apiproxy/policies/AM-SetResponse.xml#L19

The contents of the value field in the response payload should use escapeJSON to guarantee that the response sent to the client will be valid JSON.

More info in: https://docs.apigee.com/api-platform/reference/message-template-intro#example-escapejson

**Comment by laughingbiscuit** [comment]
thanks @danistrebel for the fix
