### ISSUE TITLE
identity-facade: maven version min?

### ISSUE THREAD

**Issue by g-lalevee** [apigee/devrel#279]
Update README file (https://github.com/apigee/devrel/blob/main/references/identity-facade/README.md) to indicate maven version min required:  >= 3.6.1 ?

Version 3.6.0 returns error:
```
Unrecognized option: -ntp
Unable to parse command line options: Unrecognized option: -ntp
usage: mvn [options] [<goal(s)>] [<phase(s)>]
```

**Comment by laughingbiscuit** [comment]
previously 3.6.1 was the lowest. we have removed `-ntp` to improve compatibility. this was tested 3.6.0
