### ISSUE TITLE
should pipeline.sh be a dotfile?

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/devrel#29]
E.g. If I have an identity-v1 reference project in devrel, as a reader I might think that pipeline.sh is required in my own project. Hiding it could be useful.

**Comment by seymen** [comment]
shall we change it's name (yet again!) to `devrel-pipeline.sh`? That way it is pretty obvious what this file is for. What do you think?

**Comment by seymen** [comment]
..as discussed pipeline might be useful for other people as quick start instructions.
