### ISSUE TITLE
Sackmesser deploy shared flow

### ISSUE THREAD

**Issue by tyayers** [apigee/devrel#332]
Is it possible?  Tried with this test repo, couldn't get it to work: https://github.com/tyayers/apigee-odata-converter

Used this command: ./sackmesser deploy -g https://github.com/tyayers/apigee-odata-converter --googleapi -t "$TOKEN" -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --debug

But only get this output back (doesn't do anything): 
[DEBUG] Apigee OAuth2 access token: ya29.a0A...
[DEBUG] Sackmesser command: deploy
[INFO] removing /home/tyayers/Projects/devrel/tools/apigee-sackmesser/bin/deploy-1626163856-9332

Thanks in advance for any hints..

**Comment by danistrebel** [comment]
thanks Tyler!

The github link made the assumption that you encoded the repo that included a branch

for you this would be `https://github.com/tyayers/apigee-odata-converter/tree/main/` 

I see that this isn't necessarily the expectation if you want to deploy the root of main branch of a repo. I'll add this option as well.

**Comment by tyayers** [comment]
Ah that makes sense, didn't notice the branch part in the example, thanks for clarifying / checking on default handling..
