### ISSUE TITLE
sackmesser - create base config file if missing

### ISSUE THREAD

**Issue by danistrebel** [apigee/devrel#338]
the base config file in the root of the proxy bundle is not required and people coming from apigeetool might not have it in their repo. Sackmesser should generate a plain base config such that these deployments no longer error out.

@markjkelly please comment if I missed any requirement, thx

**Comment by markjkelly** [comment]
You've captured it correctly @danistrebel - I believe this is the corresponding functionailty in ApigeeTool -> ([https://github.com/apigee/apigeetool-node/blob/59cd6a4a0133dcfee627bb1387070cb40f4f8254/lib/commands/deployproxy.js#L247](link))

**Comment by danistrebel** [comment]
This should be handled in the maven plugin instead. Until then Sackmesser requires a complete proxy bundle.
