### ISSUE TITLE
Using quota and spikearrest in oas-apigee-mock tool

### ISSUE THREAD

**Issue by Neetu1231** [apigee/devrel#368]
1) how can I use spike Arrest and quota policies in oas-apigee-mock tool?
2) And also if I want to throw statusCode=400 bad request then how can I use validations like if I am using wrong url then it pick response from assign message policy and thow it?
For success statusCode it is working fine but for other requests it simply throw 200ok blank response but dnt decide which error to throw
Is there anyway to automate this as well?

**Comment by danistrebel** [comment]
I'll do my best to answer this but @markjkelly can probably provide more insights into this.

1. the `oas-apigee-mock` tool does not generate spike arrest or quota policies but you can obviously add it to the generated proxies yourself if needed.

2. The integration test handles the 400 error case here: https://github.com/apigee/devrel/blob/main/tools/oas-apigee-mock/test/features/orders-apikey-query.feature#L37-L39 .

for the blank 200 OK can you provide us with a) the curl command b) the method in OAS and c) the expected result that is different from the blank 200?

**Comment by Neetu1231** [comment]
@danistrebel  I tried to add spike arrest by adding code in generateProxyendpoint.js file and generate it using -t in command which we are using to generate proxy.

And what is the use of policy_templates inside lib (spikearrest,quota,security etc) .Are we using it somewhere?

**Comment by danistrebel** [comment]
@Neetu1231 of course we're also very happy to review a PR if you want to push the code you used to generate the proxy with spike arrest and/or quota policies to the upstream here.

**Comment by markjkelly** [comment]
Hi @danistrebel @Neetu1231 - That's right, not all of the policy templates are currently being used, depending on demand/need I was planning to add spike arrest and quota functionality at some point.

**Comment by Neetu1231** [comment]
@markjkelly @danistrebel  Rather then removing ,can we add some logic which can use both spike and quota and also some basic auth functionality atleast.Would be great,meanwhile I will try to share the code which I have added to use spike arrest policy,without those templates which you have added it wont be possible so kindly dnt remove that.

**Comment by danistrebel** [comment]
@Neetu1231 I suggest we'll close this here. The templates are still available though the git history so you are of course free to use them from there.

If you think the mock generator should still include spike arrest and or quota policies you are more than welcome to submit a PR for review.
