### ISSUE TITLE
Sackmesser: apigee X token auth not working with apigee edge maven plugin 2.1.2

### ISSUE THREAD

**Issue by fourlincoln10** [apigee/devrel#369]
When I try and deploy a proxy to Apigee X using sackmesser:

```
export APIGEE_BUILD_TOKEN=$(gcloud auth print-access-token)

sackmesser deploy -d "$PWD/my-proxy" \
--googleapi \
-t "$APIGEE_BUILD_TOKEN" \
-o "my-org" \
-e "test" \
-b "/my-basepath"
```

I receive this error message:
```
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:2.1.2:deploy (deploy-bundle-step) on project apigee-deployer: Username and password must be provided for basic authentication.
```

In order to fix it, I had to downgrade the apigee.plugin.version property in the pom-hybrid.xml file to 2.1.1.

```
<apigee.plugin.version>2.1.2</apigee.plugin.version>
```

to 

```
<apigee.plugin.version>2.1.1</apigee.plugin.version>
```

**Comment by danistrebel** [comment]
Hi Troy, Thanks for creating the issue, much appreciated!

I am trying to reproduce the issue you're facing but failed in that I succeeded with my deployment with the current configuration.

I tried with one of the DevRel proxies such that we can have a common ground:

```sh
export APIGEE_BUILD_TOKEN=$(gcloud auth print-access-token)

./tools/apigee-sackmesser/bin/sackmesser deploy -d "./references/js-callout" \                                                                                                                                   
  --googleapi \
  -t "$APIGEE_BUILD_TOKEN" \
  -o "my-org" \
  -e "test" \
  -b "/my-basepath"
```

Also, we're using Sackmesser to deploy most of our DevRel proxies nightly and the auth hasn't been an issue even after bumping the apigee maven plugin version to support Google authentication for the backend calls.

Do you have any other information about your proxy, environment that would help us identify your experience is different from what we see on our side?

**Comment by fourlincoln10** [comment]
Hi Dan,

Thank you for taking the time to look into this. I think this is specific to my local workstation environment because I am now using sackmesser with the current maven plugin to deploy apigee resources in a ci/cd pipeline and I'm not getting any errors in the pipeline. I'll close this issue for now and re-open if I bump into it again.
