### ISSUE TITLE
The identity-facade product creation fails 

### ISSUE THREAD

**Issue by imanzarrabian** [apigee/devrel#459]
Hey all, 
the sackmesser build fails on my side when creating the API product and referring to "identity-facade-v1". 
The only proxy I see is "identity-facade" (without the v1 suffix).
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.5.2:apiproducts (create-config-apiproduct) on project identity-facade: Apigee network call error 400 Bad Request
{
  "code" : "keymanagement.service.InvalidProxy",
  "message" : "Invalid apiproxy identity-facade-v1",
  "contexts" : [ ]
}
```
I will create a small PR for this and sorry if the issue is more complex than this :)

**Comment by OmidTahouri** [comment]
This was fixed by #458
