### ISSUE TITLE
Error in hybrid-quickstart initialize-runtime-gke.sh

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/devrel#481]
Tried this on Argolis.
Seems to be related to create_sa() as no workload SAs were created.
Perhaps I have a constraint that's blocking.

```
🏢 Letting Google manage the cert - test
managedcertificate.networking.gke.io/apigee-xlb-cert created
backendconfig.cloud.google.com/ingress-backendconfig created
ingress.networking.k8s.io/xlb-apigee-ingress created
namespace/apigee created
gateway.networking.istio.io/apigee-wildcard created
virtualservice.networking.istio.io/health created

[ERROR]: More than one -e is entered
```

**Comment by kurtkanaskie** [comment]
Ahah!

If I have ENV set as an environment level it fails due to this case in create-service-account
```
        -e|--env)
            # Checks $2 is not empty and is not another flag by checking for "-".
            if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; 
            then
                [[ -n "${ENV}" ]] && log_error "More than one $1 is entered"
                ENV=$2
                shift 2
                continue
            fi
            log_error "Argument for $1 is missing" >&2
            ;;
```

**Comment by danistrebel** [comment]
Thanks for giving it a spin, @kurtkanaskie ! I hope you liked the new workload identity feature ;).

I reckon there's a few environment variables used by the create sa script and also the install_asm. These scripts are not maintained by us so keeping a list of all ENV variables that are used in there are probably not a feasible option.

How did you solve it in the end? `bash -i ./inititalize-gke.sh`?

**Comment by kurtkanaskie** [comment]
I unset the environment variable "ENV".

The tool expects "ENV_NAME" to be set, although the script that gets installed here:\
`./tools/apigeectl/apigeectl_1.6.5/tools/create-service-account` \
tests "ENV".

**Comment by danistrebel** [comment]
The create-service-account script's ENV parameter is only accepting `prod|non-prod` and we pass it the `-e` attribute here: 
 https://github.com/apigee/devrel/blob/main/tools/hybrid-quickstart/steps.sh#L639 

The ENV_NAME variable in this script is relelated to the Apigee Environments and not related to the usage in the service account script.

If you're observing any unexpected side effects with the create-service-account script from having an ENV configured in your context then please report it with the maintainers for apigeectl. We're taking that script straight from there and the ENV side effect would also manifest itself outside of the quickstart.

**Comment by kurtkanaskie** [comment]
Created b/224772541

**Comment by kurtkanaskie** [comment]
Closing as this is just a side effect of extra environment variables.
