### ISSUE TITLE
ERROR: Something is wrong with your Location configuration, as APIGEE_ENDPOINT is equal null

### ISSUE THREAD

**Issue by wely** [apigee/devrel#576]
Followed the instruction here (https://cloud.google.com/apigee/docs/api-platform/system-administration/shared-vpcs#configure-the-service-project) and got this error: 
Step 7b: Set up environment variables
Check that APIGEE_ENDPOINT is not null: null
ERROR: Something is wrong with your Location configuration, as APIGEE_ENDPOINT is equal null

**Comment by danistrebel** [comment]
We looked at this 1:1 and discovered that there were errors before that point that were cause by the network not being available for service networking.
