### ISSUE TITLE
recaptcha-enterprise could use data capture

### ISSUE THREAD

**Issue by srinandan** [apigee/devrel#587]
I think it is a good idea to include the data capture policy with reCAPTCH to store the risk scores and possibly even recommend custom reports for it.

**Comment by danistrebel** [comment]
Great suggestion, thanks!
@JoelGauci do you want to pick this up?

**Comment by JoelGauci** [comment]
Yes very good idea

**Comment by JoelGauci** [comment]
Hello @srinandan , issue #587 has been solved
