### ISSUE TITLE
Error when deploying a proxy linked to a GCP service account (ApigeeX new feature)

### ISSUE THREAD

**Issue by ochaoui** [apigee/devrel#634]
Hello folks,

I am testing apigee-sackmesser to deploy a proxy that is linked to a GCP service account (new feature in ApigeeX).

When I configure it via the GUI, everything works like a charm :
- I configure the target with the <Authentication> tag 
![image](https://user-images.githubusercontent.com/78160239/209831674-b3194b5e-8abb-4b54-b7d6-a9badf04a9a2.png)

- When I deploy the proxy, I add the GCP service account that has the right roles :
![image](https://user-images.githubusercontent.com/78160239/209831988-ab6e5167-d2b3-47ce-81d6-0d45e6887889.png)

This config works well !

Now I tried to do that via apigee-sackmesser.
The problem is I do not know where should I put the service account name in order to deploy it ... In the edge.json or somewhere in the apiproxy bundle ?
![image](https://user-images.githubusercontent.com/78160239/209832302-b541e841-7546-4b4d-bdd1-97d3e9133d38.png)

Here is the error I get after running sackmesser :
![image](https://user-images.githubusercontent.com/78160239/209832607-eadfd024-c121-4c87-bb16-6118734ee40f.png)

Can you please help me with that ?

Regards,

**Comment by OmidTahouri** [comment]
Hi @ochaoui -- you should just add the `--deployment-sa` argument to the `sackmesser deploy` command, as explained in the output of [`sackmesser help`](https://github.com/apigee/devrel/tree/main/tools/apigee-sackmesser#general-usage)

I hope this helps!

_As a side note, please take note of the documented [Apigee Antipatterns](https://cloud.google.com/apigee/docs/api-platform/antipatterns/intro) which [discourages proxying requests to the Apigee API](https://cloud.google.com/apigee/docs/api-platform/antipatterns/invoking-management) for a variety of reasons._

**Comment by OmidTahouri** [comment]
Hi @ochaoui -- I'm going to close this due to not hearing back. I'll assume you're able to resolve with the comment above.
