### ISSUE TITLE
Add product via edge.json : created with a legacy format

### ISSUE THREAD

**Issue by bluewolf26** [apigee/devrel#645]
Hello folks !

I am trying to add a product via sackmesser and it's edge.json.
I followed the example in the maven repo :
![image](https://user-images.githubusercontent.com/46425894/217541220-0b28bcab-eae3-4bbf-92ee-9a0279f4c18d.png)

When I deploy via sackmesser, I obtain this error :
![Untitled](https://user-images.githubusercontent.com/46425894/217541359-207c7574-3e8e-4b99-a767-7b31808dc53a.png)

Do you know how to solve this ?

**Comment by OmidTahouri** [comment]
@bluewolf26 I'm going to close this issue as we've not heard back since last week. Thanks!
