### ISSUE TITLE
Sackmesser - Two apikeys getting created while migrating apps.

### ISSUE THREAD

**Issue by mahesh-kannekanti** [apigee/devrel#659]
While migrating existing APPS from Onprem to Hybrid using Sackmesser deploy option Apigee is generating an API Key out of the box APIKey and creating the second key using the input provided. So each migrated app is having 2 apikeys.

Is there any way we can create the app using just the API Key that is provided as input?

**Comment by OmidTahouri** [comment]
You're observation is correct -- new credentials are generated by default, even when importing existing credentials. I recommend migrating your existin apps and credentials, before later cleaning up the generated credential from each app as a separate step. You should be able to easily and programmatically identify which credential to delete, as you won't see any API Products in the credential. When importing the existing credentials, ensure you're including the appropriate API Product(s).

Please note that this is not an issue Sackmesser and is the behaviour of the Apigee API that Sackmesser interacts with.

**Comment by mahesh-kannekanti** [comment]
Thanks for the response OmidTahouri.

For the new api keys we are seeing that it is adding the same product we provide for the existing key.
