### ISSUE TITLE
[Idea] Reference Shared Flow for GCP Service Account Tokens

### ISSUE THREAD

**Issue by danistrebel** [apigee/devrel#85]
To use GCP services from Apigee most services require a service account access or identity token to be available from within a flow.

Apigee SaaS provides an [extension](https://docs.apigee.com/api-platform/reference/extensions/google-authentication/google-authentication-extension-102) but has the following short comings:
- not available in hybrid
- no key rotation possible
- no flexibility over where to store the SA key

A shared flow could be added to perform the following tasks
- lookup access tokens in cache
- exchange a SA key for an access / id token
- cache the token for later use

**Comment by seymen** [comment]
:+1: I would like an extension like this. We can then ask the docs team to put a link to this shared flow as an alternative implementation.

**Comment by danistrebel** [comment]
This is now available in https://github.com/apigee/devrel/tree/main/references/gcp-sa-auth-shared-flow
